### ISSUE TITLE
Moonscript not loading

### ISSUE THREAD

**Issue by MightyAlex200** [JanWerder/vscode-love-launcher#1]
When running via terminal, Löve works perfectly fine when loading the `moonscript` module, but when using this extension, it doesn't let Moonscript override the default `require` function. Because of that, no `.moon` files can be opened.

Using Manjaro
Kernel `4.4.39-1-MANJARO`
Löve in `/usr/bin/love`

**Comment by JanWerder** [comment]
Does this issue still persist?
