### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gforcedev** [JanWerder/vscode-love-launcher#4]
bug: love2d refuses to respond after using alt+L
recreate: openVSCode, and use alt+L to open my project (this works fine). Do it again, and the love2d window stops responding.

additional information:
I am on windows, running vscode off a memory stick portably with batch file:
        *code.exe --user-data-dir "userdata" --extensions-dir "ext"*

**Comment by JanWerder** [comment]
Can't reproduce it with v.1.0.7
