### ISSUE TITLE
vscode not working with love2d

### ISSUE THREAD

**Issue by ghost** [JanWerder/vscode-love-launcher#6]
i installed the love launcher, and i did alt-l

and i get:

![](https://i.gyazo.com/a0deed9c66b9f19c41f7c1f0458068ab.png)

any idea?

ty in advance!

my code:
```
function love.draw()
    love.graphics.print("Hello World!", 400, 300)
end
```

**Comment by ghost** [comment]
i found a temp fix for now

```
                var process = exec(path, ['C:\\Users\\Administrator\\Desktop\\myFOLDER', "--console"], function (err, data) {
                });
```

inside `extensions.js`, at `C:\Users\Administrator\.vscode\extensions\janw.love-launcher-1.0.5\out\src`

for temporary fix!

**Comment by JanWerder** [comment]
The path new path calculation fixes this issue.
Thanks for reporting
