### ISSUE TITLE
Launcher is opening löve at the wrong path (macOS 11.2.3, latest löve and löve launcher)

### ISSUE THREAD

**Issue by lhvy** [JanWerder/vscode-love-launcher#8]
When I launch using this extension, it launches including the full path to the file instead of the folder containing the file, causing this issue.
```
Error: [string "boot.lua"]:577: Cannot load game at path '/Users/lhvy/Documents/Love/hello-world/main.lua'.
Make sure a folder exists at the specified path.
```

I can replicate that in my terminal by running `/Applications/love.app/Contents/MacOS/love main.lua` instead of the usual `/Applications/love.app/Contents/MacOS/love .` while my working directory is the project folder.

Is this issue specific to macOS? I am unable to check right now but I will test later.

**Comment by JanWerder** [comment]
Thank you for your report, this should be fixed with https://github.com/JanWerder/vscode-love-launcher/commit/3f84e1c773944dde5524009b2c3842a3663091b8 .
Can you check if it works for you?

**Comment by lhvy** [comment]
Yep! The latest update works perfectly. Thanks for the quick response and fix!
